# SPDX-License-Identifier: LGPL-3.0-only

---
# defaults file for base

base_sysadmin_ssh_pubkey: ""

# Show directory path (do not include pki)
base_show_sub_dirs:
  - nats
  - ingest
  - vision
  - hearing
  - brain
  - output
  - health_check
