# SPDX-License-Identifier: LGPL-3.0-only
---
galaxy_info:
  author: Anthony Tilelli
  description: Install physical Configuration for the AI Improv Toolkit. This task assumes task select "laptop" has been selected.
  company: N/A
  license: LGPL-3.0-only
  min_ansible_version: 2.20.1
  galaxy_tags: []
dependencies: []
