# SPDX-License-Identifier: LGPL-3.0-only
---
# handlers file for ingest

- name: Udev reload
  block:
    - name: Reload udev rules
      ansible.builtin.command: udevadm control --reload-rules
      changed_when: false

    - name: Trigger udev to apply new rules
      ansible.builtin.command: udevadm trigger
      changed_when: false

    - name: Wait for udev to settle
      ansible.builtin.command: udevadm settle
      changed_when: false
